version: "3.7"
services:
  app:
    build:
      args:
        user: usuario
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: demo
    container_name: demo-app
    environment:
      PHP_POST_MAX_SIZE: 256M
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php.ini:/usr/local/etc/php/php.ini
    networks:
      - netdemo

  db:
    image: mysql:8.0
    container_name: demodb
    restart: unless-stopped
    ports:
      - 3356:3306
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - netdemo

  nginx:
    image: nginx:alpine
    container_name: demo-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - netdemo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    container_name: demo-phpmyadmin
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - netdemo
  
  node:
    image: node:20.2
    container_name: demo-node
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    tty: true
    networks:
      - netdemo

networks:
  netdemo:
    driver: bridge
